CREATE TABLE BA_CONTRACT_CATEGORIES
(
  CATEGORY_ID    VARCHAR2(20 BYTE)              NOT NULL,
  SHORTNAME      VARCHAR2(50 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(100 BYTE),
  CREATED_BY     VARCHAR2(10 BYTE)              NOT NULL,
  CREATION_DATE  DATE                           DEFAULT sysdate               NOT NULL,
  CHANGED_BY     VARCHAR2(1 BYTE),
  CHANGE_DATE    DATE,
  TRANSPORT_ID   VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BA_CONTRACT_DISTRIBUTIONS
(
  DISTRIBUTION_ID  VARCHAR2(20 BYTE)            NOT NULL,
  SHORTNAME        VARCHAR2(50 BYTE)            NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE),
  CREATED_BY       VARCHAR2(10 BYTE)            NOT NULL,
  CREATION_DATE    DATE                         DEFAULT sysdate               NOT NULL,
  CHANGED_BY       VARCHAR2(1 BYTE),
  CHANGE_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BA_CONTRACT_EXCISES
(
  EXCISE_ID      VARCHAR2(20 BYTE)              NOT NULL,
  SHORTNAME      VARCHAR2(50 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(100 BYTE),
  CREATED_BY     VARCHAR2(10 BYTE)              NOT NULL,
  CREATION_DATE  DATE                           DEFAULT sysdate               NOT NULL,
  CHANGED_BY     VARCHAR2(1 BYTE),
  CHANGE_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BA_CONTRACT_GROUPS
(
  GROUP_ID       VARCHAR2(20 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(10 BYTE)              NOT NULL,
  CREATION_DATE  DATE                           DEFAULT sysdate               NOT NULL,
  CHANGED_BY     VARCHAR2(1 BYTE),
  CHANGE_DATE    DATE,
  SHORTNAME      VARCHAR2(50 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(100 BYTE),
  GROUP_TYPE     VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BA_CONTRACT_TRANSPORTS
(
  TRANSPORT_ID   VARCHAR2(20 BYTE)              NOT NULL,
  SHORTNAME      VARCHAR2(50 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(100 BYTE),
  CREATED_BY     VARCHAR2(10 BYTE)              NOT NULL,
  CREATION_DATE  DATE                           DEFAULT sysdate               NOT NULL,
  CHANGED_BY     VARCHAR2(1 BYTE),
  CHANGE_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACTS
(
  CONTRACT_ID           NUMBER,
  CONTRACT_SERIES       VARCHAR2(10 BYTE),
  CONTRACT_NUMBER       NUMBER                  NOT NULL,
  CONTRACT_DATE         DATE                    NOT NULL,
  CONTRACT_EXPIRE_DATE  DATE,
  INVOICE_CLIENT_ID     VARCHAR2(10 BYTE),
  EMAIL                 VARCHAR2(100 BYTE),
  CREATION_DATE         DATE                    DEFAULT sysdate               NOT NULL,
  CREATED_BY            VARCHAR2(10 BYTE)       DEFAULT 'WWW'                 NOT NULL,
  CHANGE_DATE           DATE,
  CHANGED_BY            VARCHAR2(10 BYTE),
  DESCRIPTION           VARCHAR2(2000 BYTE),
  SHORTNAME             VARCHAR2(50 BYTE),
  CONTRACT_TYPE         VARCHAR2(10 BYTE),
  FINISH_DATE           DATE,
  STATUS                VARCHAR2(20 BYTE),
  SINGNATURE_DATE       DATE,
  INVOICE_ADDRESS_NR    NUMBER,
  DELIVERY_ADDRESS_NR   NUMBER,
  AGENT_ID              VARCHAR2(10 BYTE),
  AGENT_COMM            NUMBER,
  START_DATE            DATE,
  REPEAT_PERIOD         VARCHAR2(10 BYTE),
  ADVANCE_YN            CHAR(1 BYTE)            DEFAULT 'N',
  TERM_OF_PAYMENT_ID    NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACTS_WIZARD
(
  PROCESSING_ID       NUMBER,
  INVOICE_DATE        DATE,
  INVOICE_CLIENT_ID   VARCHAR2(10 BYTE),
  INVOICE_ADDRESS_NR  NUMBER,
  PRODUCT_ID          VARCHAR2(30 BYTE),
  DISCOUNT            NUMBER,
  AGENT_ID            VARCHAR2(10 BYTE),
  CREATION_DATE       DATE,
  CREATED_BY          VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_ADDRESSES
(
  CONTRACT_ID                 NUMBER,
  ADDRESS_KEY                 VARCHAR2(10 BYTE),
  ADDRESS_NR                  NUMBER,
  RESERVED_CAPACITY           NUMBER,
  CONSUMER_ID                 NUMBER,
  CREATION_DATE               DATE,
  CREATED_BY                  VARCHAR2(10 BYTE),
  CHANGE_DATE                 DATE,
  CHANGED_BY                  VARCHAR2(1 BYTE),
  DISTRIBUTION_ID             VARCHAR2(20 BYTE),
  BASE_COST                   NUMBER,
  SUPPLY_COST                 NUMBER,
  OPERATIONAL_COST            NUMBER,
  DISCOUNT                    NUMBER,
  EXCISE_ID                   VARCHAR2(20 BYTE),
  CAPACITY_COST               NUMBER,
  CATEGORY_ID                 VARCHAR2(20 BYTE),
  TRANSPORT_COST              NUMBER,
  VALID_FROM                  DATE,
  VALID_TO                    DATE,
  ADDITIONAL_CONTRACT_NUMBER  VARCHAR2(30 BYTE),
  IN_PRICE_CAPACITY_YN        CHAR(1 CHAR)      DEFAULT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_COSTS
(
  TYPE_ID        VARCHAR2(20 BYTE),
  COST_KEY       VARCHAR2(20 BYTE),
  GROUP_ID       VARCHAR2(20 BYTE),
  COST_VALUE     NUMBER,
  VALID_FROM     DATE,
  CREATED_BY     VARCHAR2(10 BYTE),
  CREATION_DATE  DATE,
  CHANGED_BY     VARCHAR2(10 BYTE),
  CHANGE_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_INDEXES
(
  INDEX_DATE     DATE                           NOT NULL,
  INDEX_START    NUMBER                         NOT NULL,
  INDEX_END      NUMBER                         NOT NULL,
  CONSUMER_ID    VARCHAR2(100 BYTE)             NOT NULL,
  CREATION_DATE  DATE,
  CREATED_BY     VARCHAR2(10 BYTE),
  CHANGE_DATE    DATE,
  CHANGED_BY     VARCHAR2(10 BYTE),
  PCS            NUMBER,
  STATUS         VARCHAR2(10 BYTE),
  ERROR_MESSAGE  VARCHAR2(255 BYTE),
  CHECK_DATE     DATE,
  PROCESSING_ID  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_PERIODS
(
  CONTRACT_ID    NUMBER,
  PERIOD_START   DATE,
  PERIOD_END     DATE,
  REMARKS        VARCHAR2(500 BYTE),
  CREATED_BY     VARCHAR2(10 BYTE),
  CREATION_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_WIZARDS
(
  PROCESSING_ID    NUMBER,
  PROCESSING_DATE  DATE,
  SHORTNAME        VARCHAR2(100 BYTE),
  CREATION_DATE    DATE,
  CREATED_BY       VARCHAR2(10 BYTE),
  RUN_TYPE         VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CL_CONTRACT_WIZARD_DETAILS
(
  PROCESSING_ID       NUMBER,
  INVOICE_DATE        DATE,
  INVOICE_CLIENT_ID   VARCHAR2(10 BYTE),
  INVOICE_ADDRESS_NR  NUMBER,
  CONTRACT_ID         NUMBER,
  PRODUCT_ID          VARCHAR2(30 BYTE),
  DISCOUNT            NUMBER,
  AGENT_ID            VARCHAR2(10 BYTE),
  CREATION_DATE       DATE,
  CREATED_BY          VARCHAR2(10 BYTE),
  VALUE               NUMBER                    DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BA_CONTRACT_CATEGORIES_PK ON BA_CONTRACT_CATEGORIES
(CATEGORY_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BA_CONTRACT_GROUPS_PK ON BA_CONTRACT_GROUPS
(GROUP_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CL_CONTRACTS_PK ON CL_CONTRACTS
(CONTRACT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CL_CONTRACT_COSTS_PK ON CL_CONTRACT_COSTS
(TYPE_ID, COST_KEY, VALID_FROM, GROUP_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CL_CONTRACT_WIZARDS_PK ON CL_CONTRACT_WIZARDS
(PROCESSING_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CL_CONTRACT_WIZARD_DETAILS ON CL_CONTRACT_WIZARD_DETAILS
(PROCESSING_ID, CONTRACT_ID)
LOGGING
NOPARALLEL;


ALTER TABLE BA_CONTRACT_CATEGORIES ADD (
  CONSTRAINT BA_CONTRACT_CATEGORIES_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX BA_CONTRACT_CATEGORIES_PK
  ENABLE VALIDATE);

ALTER TABLE BA_CONTRACT_GROUPS ADD (
  CONSTRAINT BA_CONTRACT_GROUPS_PK
  PRIMARY KEY
  (GROUP_ID)
  USING INDEX BA_CONTRACT_GROUPS_PK
  ENABLE VALIDATE);

ALTER TABLE CL_CONTRACTS ADD (
  CONSTRAINT CL_CONTRACTS_PK
  PRIMARY KEY
  (CONTRACT_ID)
  USING INDEX CL_CONTRACTS_PK
  ENABLE VALIDATE);

ALTER TABLE CL_CONTRACT_WIZARDS ADD (
  CONSTRAINT CL_CONTRACT_WIZARDS_PK
  PRIMARY KEY
  (PROCESSING_ID)
  USING INDEX CL_CONTRACT_WIZARDS_PK
  ENABLE VALIDATE);

ALTER TABLE CL_CONTRACT_WIZARD_DETAILS ADD (
  CONSTRAINT CL_CONTRACT_WIZARD_DETAILS
  PRIMARY KEY
  (PROCESSING_ID, CONTRACT_ID)
  USING INDEX CL_CONTRACT_WIZARD_DETAILS
  ENABLE VALIDATE);

ALTER TABLE CL_CONTRACT_ADDRESSES ADD (
  CONSTRAINT CL_CONTRACT_ADDRESSES_FK1 
  FOREIGN KEY (CONTRACT_ID) 
  REFERENCES CL_CONTRACTS (CONTRACT_ID)
  ENABLE VALIDATE);
